spring:
  datasource:
    url: jdbc:sqlite:contacts.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${S3_BUCKET_NAME}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}